site_name: 钱学森班学习指南
site_description: 钱学森班课程与学习指引站点
site_author: 钱学组
repo_name: XJTU-QXZ/QXSCourses    
repo_url: https://github.com/XJTU-Qian-Xuesen-Class/XJTU-QXZ  # 仓库地址
docs_dir: docs
theme:
 name: material
 icon:
   logo: material/library
   language: zh
 
 palette:
  
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 夜间模式

    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 白天模式
 features:
    - header.repo
    - navigation.tabs #多个分类标签
    - navigation.top #顶部导航
    - search.highlight #搜索高亮
    - navigation.expand #展开导航
    - navigation.sections #导航分组
    - navigation.instant #即时导航
    - search.suggest #搜索建议
    - layout.footer #页脚
    - toc.follow #目录跟随
    - navigation.tracking #导航追随
    - content.code.copy #代码复制

nav:
  - 主页:
    - 主页: 主页/index.md
    - 贡献指南: 主页/contribution_guide.md
    - 课程页面模板: 主页/course_template.md
  - 思政军体课:
    - 思政军体课: 思政军体课/political_military_course.md
    - 形式与政策 I: 思政军体课/form_and_policy_I.md
    - 思想道德与法治: 思政军体课/ideology_and_law.md
    - 中国近现代史纲要: 思政军体课/modern_chinese_history.md
    - 马克思主义基本原理: 思政军体课/marxism_basic_principles.md
    - 毛泽东思想和中国特色社会主义理论体系概论: 思政军体课/mao_zedong_thought_and_socialism_with_chinese_characteristics.md
    - 习近平新时代中国特色社会主义思想: 思政军体课/xi_jinping_thought_on_socialism_with_chinese_characteristics.md
    - 形式与政策 II: 思政军体课/form_and_policy_II.md
    - 军事理论: 思政军体课/military_theory.md
  - 通识选修课:
    - 通识选修课: 通识选修课/general_elective_course.md
    - 通识核心课: 通识选修课/general_core_course.md
    - 通识选修课: 通识选修课/general_elective_course_2.md
    - 其他选修课: 通识选修课/other_elective_course.md
  - 数理基础课:
    - 数理基础课: 数理基础课/mathematical_foundations.md
    - 线性代数1: 数理基础课/linear_algebra_1.md
    - 线性代数2: 数理基础课/linear_algebra_2.md
    - 数学分析1: 数理基础课/mathematical_analysis_1.md
    - 数学分析2: 数理基础课/mathematical_analysis_2.md
    - 普通物理学1: 数理基础课/general_physics_1.md
    - 普通物理学2: 数理基础课/general_physics_2.md
    - 普通物理学实验1: 数理基础课/general_physics_experiment_1.md
    - 概率论与数理统计: 数理基础课/probability_and_statistics.md
  - 专业必修课:
    - 专业必修课: 专业必修课/professional_core_course.md
    - 程序设计与算法基础: 专业必修课/programming_and_algorithm_basics.md
    - 数据结构基础: 专业必修课/data_structure_basics.md
    - 离散数学理论基础: 专业必修课/discrete_mathematics_basics.md
    - 高级数据结构与算法分析: 专业必修课/advanced_data_structures_and_algorithm_analysis.md
    - 面向对象程序设计: 专业必修课/object_oriented_programming.md
    - 理论计算机科学导引: 专业必修课/introduction_to_theoretical_computer_science.md
    - 计算机系统 I: 专业必修课/computer_system_I.md
    - 计算机系统 II: 专业必修课/computer_system_II.md
    - 计算机系统 III: 专业必修课/computer_system_III.md
    - 人工智能引论: 专业必修课/introduction_to_artificial_intelligence.md
    - 数据库系统: 专业必修课/database_systems.md
    - 计算机网络: 专业必修课/computer_networks.md
    - 编译原理: 专业必修课/compiler_principles.md

  - 专业选修课: 专业选修课/professional_elective_course.md

  - 短学期课程: 短学期课程/short_term_courses.md

  - 跨专业课程: 跨专业课程/interdisciplinary_courses.md

  - 书评专区: 书评专区/book_reviews.md


extra:
  # 页脚可自定义内容（类似示例的存站说明、专业调整说明）
  footer:
  # 社交链接（若有需求，可配置 GitHub、公众号等）
  social:
    - icon: material/github
      #link: #链接

  navigation:
    next: 贡献指南
    next_url: 
copyright: 由钱院学辅所有
